// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: payment_service.proto

package payment_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CheckIdRepeatition(ctx context.Context, in *PaymentTransferRequest, opts ...grpc.CallOption) (*PaymentTransferResponse, error)
	RegistrationApplication(ctx context.Context, in *PaymentTransferRequest, opts ...grpc.CallOption) (*PaymentTransferResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CheckIdRepeatition(ctx context.Context, in *PaymentTransferRequest, opts ...grpc.CallOption) (*PaymentTransferResponse, error) {
	out := new(PaymentTransferResponse)
	err := c.cc.Invoke(ctx, "/payment_service.PaymentService/CheckIdRepeatition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) RegistrationApplication(ctx context.Context, in *PaymentTransferRequest, opts ...grpc.CallOption) (*PaymentTransferResponse, error) {
	out := new(PaymentTransferResponse)
	err := c.cc.Invoke(ctx, "/payment_service.PaymentService/RegistrationApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations should embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	CheckIdRepeatition(context.Context, *PaymentTransferRequest) (*PaymentTransferResponse, error)
	RegistrationApplication(context.Context, *PaymentTransferRequest) (*PaymentTransferResponse, error)
}

// UnimplementedPaymentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) CheckIdRepeatition(context.Context, *PaymentTransferRequest) (*PaymentTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIdRepeatition not implemented")
}
func (UnimplementedPaymentServiceServer) RegistrationApplication(context.Context, *PaymentTransferRequest) (*PaymentTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationApplication not implemented")
}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CheckIdRepeatition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CheckIdRepeatition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment_service.PaymentService/CheckIdRepeatition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CheckIdRepeatition(ctx, req.(*PaymentTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_RegistrationApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RegistrationApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment_service.PaymentService/RegistrationApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RegistrationApplication(ctx, req.(*PaymentTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_service.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIdRepeatition",
			Handler:    _PaymentService_CheckIdRepeatition_Handler,
		},
		{
			MethodName: "RegistrationApplication",
			Handler:    _PaymentService_RegistrationApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_service.proto",
}
